// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyCaNXQ0b0soREbCnP9wYEHTyKdM0H_Zc',
    appId: '1:653707740198:web:a2a57bb6fa669caffa12e7',
    messagingSenderId: '653707740198',
    projectId: 'teamskills-d44d3',
    authDomain: 'teamskills-d44d3.firebaseapp.com',
    storageBucket: 'teamskills-d44d3.appspot.com',
    measurementId: 'G-SVDRXV5ZSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMv3SCECyBlEjsYL5ZR3bQxatElqncWG0',
    appId: '1:653707740198:android:5bfba9c5084fe79cfa12e7',
    messagingSenderId: '653707740198',
    projectId: 'teamskills-d44d3',
    storageBucket: 'teamskills-d44d3.appspot.com',
  );
}
